export const COUNTRY_OPTIONS = [
  { id: "US", label: "United States" },
  { id: "CA", label: "Canada" },
  { id: "GB", label: "United Kingdom" },
  { id: "AU", label: "Australia" },
  { id: "DE", label: "Germany" },
  { id: "FR", label: "France" },
  { id: "IT", label: "Italy" },
  { id: "ES", label: "Spain" },
  { id: "NL", label: "Netherlands" },
  { id: "BE", label: "Belgium" },
  { id: "CH", label: "Switzerland" },
  { id: "AT", label: "Austria" },
  { id: "SE", label: "Sweden" },
  { id: "NO", label: "Norway" },
  { id: "DK", label: "Denmark" },
  { id: "FI", label: "Finland" },
  { id: "IE", label: "Ireland" },
  { id: "PT", label: "Portugal" },
  { id: "PL", label: "Poland" },
  { id: "CZ", label: "Czech Republic" },
  { id: "HU", label: "Hungary" },
  { id: "GR", label: "Greece" },
  { id: "RO", label: "Romania" },
  { id: "BG", label: "Bulgaria" },
  { id: "HR", label: "Croatia" },
  { id: "SI", label: "Slovenia" },
  { id: "SK", label: "Slovakia" },
  { id: "LT", label: "Lithuania" },
  { id: "LV", label: "Latvia" },
  { id: "EE", label: "Estonia" },
  { id: "LU", label: "Luxembourg" },
  { id: "MT", label: "Malta" },
  { id: "CY", label: "Cyprus" },
  { id: "JP", label: "Japan" },
  { id: "KR", label: "South Korea" },
  { id: "CN", label: "China" },
  { id: "IN", label: "India" },
  { id: "SG", label: "Singapore" },
  { id: "HK", label: "Hong Kong" },
  { id: "TW", label: "Taiwan" },
  { id: "TH", label: "Thailand" },
  { id: "MY", label: "Malaysia" },
  { id: "ID", label: "Indonesia" },
  { id: "PH", label: "Philippines" },
  { id: "VN", label: "Vietnam" },
  { id: "BR", label: "Brazil" },
  { id: "MX", label: "Mexico" },
  { id: "AR", label: "Argentina" },
  { id: "CL", label: "Chile" },
  { id: "CO", label: "Colombia" },
  { id: "PE", label: "Peru" },
  { id: "VE", label: "Venezuela" },
  { id: "UY", label: "Uruguay" },
  { id: "PY", label: "Paraguay" },
  { id: "BO", label: "Bolivia" },
  { id: "EC", label: "Ecuador" },
  { id: "ZA", label: "South Africa" },
  { id: "EG", label: "Egypt" },
  { id: "MA", label: "Morocco" },
  { id: "TN", label: "Tunisia" },
  { id: "DZ", label: "Algeria" },
  { id: "KE", label: "Kenya" },
  { id: "NG", label: "Nigeria" },
  { id: "GH", label: "Ghana" },
  { id: "IL", label: "Israel" },
  { id: "TR", label: "Turkey" },
  { id: "SA", label: "Saudi Arabia" },
  { id: "AE", label: "United Arab Emirates" },
  { id: "QA", label: "Qatar" },
  { id: "KW", label: "Kuwait" },
  { id: "BH", label: "Bahrain" },
  { id: "OM", label: "Oman" },
  { id: "JO", label: "Jordan" },
  { id: "LB", label: "Lebanon" },
  { id: "RU", label: "Russia" },
  { id: "UA", label: "Ukraine" },
  { id: "BY", label: "Belarus" },
  { id: "MD", label: "Moldova" },
  { id: "GE", label: "Georgia" },
  { id: "AM", label: "Armenia" },
  { id: "AZ", label: "Azerbaijan" },
  { id: "KZ", label: "Kazakhstan" },
  { id: "UZ", label: "Uzbekistan" },
  { id: "KG", label: "Kyrgyzstan" },
  { id: "TJ", label: "Tajikistan" },
  { id: "TM", label: "Turkmenistan" },
  { id: "MN", label: "Mongolia" },
  { id: "NZ", label: "New Zealand" },
  { id: "FJ", label: "Fiji" },
  { id: "PG", label: "Papua New Guinea" },
  { id: "NC", label: "New Caledonia" },
  { id: "VU", label: "Vanuatu" },
  { id: "SB", label: "Solomon Islands" },
  { id: "TO", label: "Tonga" },
  { id: "WS", label: "Samoa" },
  { id: "KI", label: "Kiribati" },
  { id: "TV", label: "Tuvalu" },
  { id: "NR", label: "Nauru" },
  { id: "PW", label: "Palau" },
  { id: "FM", label: "Micronesia" },
  { id: "MH", label: "Marshall Islands" },
];
